baseURL = '/'
languageCode = 'en-us'
title = 'The California Tech'
theme = 'mainroad'
paginate = "24"

[Params]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Libre+Caslon+Text:wght@400;700&display=swap"
  shortcutIcon = "bigT.png" # Shortcut icon. Path relative to "static"
  post_meta = ["date", "categories", "authors"]
  list_post_meta = ["date", "authors", "categories"]
  opengraph = true
  images = ["/bigT.png"]
  description = "The California Tech is a student-run news organization that covers the latest news and events at Caltech and beyond."
  mainSections = ["2023", "issues"]

[Params.style.vars]
  highlightColor = "#cc5709" # Override highlight color
  fontFamilyPrimary = "Georgia, serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
  fontFamilyHeadlines = "'Libre Caslon Text', serif"

[Params.sidebar]
  home = "false"
  list= "false"
  widgets = ["categories","taglist","write-for-the-tech", "editorial"]

[Params.widgets.recent]
  cached = true

[Params.widgets.categories]
  cached = true

[Params.widgets.taglist]
  cached = true


[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      attribute = true
      unsafe = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[menu]
    [[menu.main]]
      name = 'Home'
      url = '/'
      weight = 1
    [[menu.main]]
      name = 'Campus'
      url = '/categories/campus/'
      weight = 2
    [[menu.main]]
      name = 'Culture'
      url = '/categories/culture/'
      weight = 3
    [[menu.main]]
      name = 'Editorial'
      url = '/categories/editorial/'
      weight = 5
    [[menu.main]]
      name = 'Puzzles'
      url = '/categories/puzzles/'
      weight = 6
    [[menu.main]]
      name = 'Humor'
      url = '/categories/humor/'
      weight = 7
    [[menu.main]]
      name = 'Advertising'
      url = '/Advertising/'
      weight = 100
    [[menu.main]]
      name = 'About'
      url = '/About/'
      weight = 101

[Params.CaliforniaTech]
  logo_image = "tech-fancy-2.svg"
  current_volume = "Vol. CXXVII"
  publicationDates = [
    "2023-03-03",
    "2023-04-04",
    "2023-04-11",
    "2023-04-24",
    "2023-05-16",
    "2023-05-31",
    "2023-06-13",
  ]
  publicationTags = [
    "Vol. CXXVI, Issue 1",
    "Vol. CXXVI, Issue 2",
    "Vol. CXXVI, Issue 3",
    "Vol. CXXVI, Issue 4",
    "Vol. CXXVI, Issue 5",
    "Vol. CXXVI, Issue 6",
    "Vol. CXXVI, Issue 7",
    "Vol. CXXVII, Issue 1",
    "Vol. CXXVII, Issue 2",
  ]