baseURL = '/'
languageCode = 'en-us'
title = 'The California Tech'
theme = 'mainroad'
paginate = "100"

[Params]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Noto+Serif+Georgian:wght@500&family=Playfair+Display:wght@500;700&family=UnifrakturCook:wght@700&display=swap"
  shortcutIcon = "bigT.png" # Shortcut icon. Path relative to "static"
  post_meta = ["date", "categories", "authors"]
  list_post_meta = ["authors", "categories"]
  opengraph = true
  images = ["/bigT.png"]
  readmore = true
  description = "The California Tech is a student-run news organization that covers the latest news and events at Caltech and beyond."

[Params.style.vars]
  highlightColor = "#cc5709" # Override highlight color
  fontFamilyPrimary = "Noto Serif Georgian, serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
  fontFamilyTitle = "'UnifrakturCook', cursive"
  fontFamilyHeadlines = "'Playfair Display', serif"

[Params.sidebar]
  home = false
  widgets = ["featured","write-for-the-tech"]

[menu]
    [[menu.main]]
      name = 'Home'
      url = '/'
      weight = 1
    [[menu.main]]
      name = 'Campus'
      url = '/categories/campus/'
      weight = 2
    [[menu.main]]
      name = 'Culture'
      url = '/categories/culture/'
      weight = 3
    [[menu.main]]
      name = 'Editorial'
      url = '/categories/editorial/'
      weight = 5
    [[menu.main]]
      name = 'Puzzles'
      url = '/categories/puzzles/'
      weight = 6
    [[menu.main]]
      name = 'Humor'
      url = '/categories/humor/'
      weight = 7
    [[menu.main]]
      name = 'Advertising'
      url = '/Advertising/'
      weight = 100
    [[menu.main]]
      name = 'About'
      url = '/About/'
      weight = 101

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'