# .github/workflows/main.yml

name: Trigger Netlify Build
env:
  NETLIFY_BUILD_HOOK: ${{ vars.NETLIFY_BUILD_HOOK }}
on:
  workflow_dispatch

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
