# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 0815 daily
    - cron: '01 7 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/641e1cc2e0999f1bde5dba6a
